services:
  - type: web
    name: litellm-proxy
    runtime: image
    plan: free
    image:
      url: docker.litellm.ai/berriai/litellm-database:main-stable
    envVars:
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: LITELLM_MASTER_KEY
        sync: false
      - key: STORE_MODEL_IN_DB
        value: "True"
      - key: LITELLM_LOCAL_MODEL_COST_MAP
        value: "True"
    numInstances: 1
    healthCheckPath: /health/liveliness
    autoDeploy: false
